apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ template "fullname" . }}-api-key
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  api_key.txt: mysup3rs3cr3tap1k3yf0rwhat3v3r
