apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ template "fullname" . }}-nginx-conf
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  default.conf: |-
    server {
        listen {{ .Values.nginx.internalPort }};

        server_name _;
        root /var/www/html/public;

        index index.html;

        location ~ ^/\. {
            deny all;
        }

        # Max cache lifetime for static files & disable access logging
        location ~* \.(css|js|jpg|jpeg|gif|png|ico|gz|svg|svgz|ttf|otf|woff|woff2|eot|mp4|ogg|ogv|webm|html|htm|swf|pdf)$ {
            add_header Pragma public;
            expires max;
            access_log off;
        }

        location / {
            try_files $uri $uri/ @backend;
        }

        location @backend {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://localhost:{{ .Values.webapp.internalPort }};
        }
    }
