apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-app
    spec:
      initContainers:
      - name: copy-assets
        image: nodeapp/webapp:3
        command: ["cp", "-R", "/code/public", "/var/www/html"]
        volumeMounts:
        - mountPath: /var/www/html
          name: pub-files
      containers:
      - name: nginx
        image: joerx/nginx-proxy
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: NGINX_PORT
          value: '8000'
        - name: NGINX_ROOT
          value: /var/www/html/public
        - name: PROXYPASS_PORT
          value: '3000'
        - name: PROXYPASS_HOST
          value: localhost
        volumeMounts:
        - mountPath: /var/www/html
          name: pub-files
      - name: webapp
        image: nodeapp/webapp:3
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_PORT
          value: '3000'
        volumeMounts:
        - mountPath: /code/config
          name: app-config
        - mountPath: /code/secrets
          name: app-apikey
      volumes:
      - name: pub-files
        emptyDir: {}
      - name: app-config
        configMap:
          name: nodeapp-config
      - name: app-apikey
        secret:
          secretName: nodeapp-apikey
